# The name of your workflow.
name: Deploy Jekyll site to Pages

on:
  # Runs on pushes targeting the default branch.
  push:
    branches: ["main"] # Or "master", depending on your repo's default branch

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages.
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Make sure this Ruby version matches the one in your .ruby-version file or Gemfile.
          ruby-version: '3.1' 
          # This caches your dependencies for faster builds.
          bundler-cache: true 
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        # This command runs `bundle install` and then builds your site.
        run: bundle exec jekyll build --destination ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
